name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Github release
        uses: softprops/action-gh-release@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Style check
        run: |
          make check

      - name: Run test
        run: |
          make test

      - name: Publish package to PyPI
        run: |
          make publish
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
